---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by loon.
--- DateTime: 2021/12/1 5:35 下午
---

Splash = {};
local this = Splash;

function Splash.Awake(gameObject)
    print("Splash Awake ")
    local skipButton = GameObject.Find("SkipButton").gameObject;
    local luaBehaviour = gameObject:GetComponent('LuaBehaviour');
    luaBehaviour:AddClick(skipButton,this.clickEvent)
end

function Splash.Start()
    print("Splash Start ")
end



function Splash.clickEvent()
    printInfo("lua clickEvent")
    SceneManager.LoadScene("HallScene")
end