---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by loon.
--- DateTime: 2021/12/3 3:09 下午
---

DEBUG = 2

defaultDomainName = "qinghuai.qixiyx.cn"
defaultDomainName2 = "qinghuai.njqixi.cn"
domainName = defaultDomainName
-- domainName = "121.199.206.10"
--domainName = "121.40.96.234"
-- domainName = "192.168.2.28"

httpDomainName = "agents.qhmj12.com"
-- httpDomainName = "agents-test.qhmj12.com"

httpVoiceDomainName = "internal.qhmj11.com"
-- httpVoiceDomainName = "internal-test.qhmj11.com"

httpKouZhaoDomainName = "activity_kouzhao.qixiyx.cn"
--httpKouZhaoDomainName = "47.110.199.23"
--httpKouZhaoDomainName = "192.168.1.137"

httpSAASName = "usercenter.qixigame.com"
--  httpSAASName = "usercenter-test.qixigame.com"

httpClubSignDomainName = "http-gateway.qixiyx.cn"  -- release
httpClubSignUploadPort = "8099" -- release
httpClubSignImageViewDownloadUrlPort = "8099"   -- release
--httpClubSignDomainName = "192.168.2.28"   -- local
--httpClubSignUploadPort = "8097" -- local
--httpClubSignImageViewDownloadUrlPort = "8095"   -- local
-- httpClubSignDomainName = "121.40.96.234"   -- test
-- httpClubSignUploadPort = "8099" -- test
-- httpClubSignImageViewDownloadUrlPort = "8099"   -- test

httpProxyDomainName = "agent.qhmj18.com"
--  httpProxyDomainName = "agent-test.qhmj18.com"
