---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by loon.
--- DateTime: 2021/12/7 4:19 下午
---
require("app.common.define")
require("app.common.functions")
json = require("cjson")
local list =
{
    "app.util.Base64",
    "app.common.config",
    "app.net.HttpRequestManager",
}

for i = 1, table.nums(list) do
    package.loaded[list[i]] = nil
end

for i = 1, table.nums(list) do
    require(list[i])
end