---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by loon.
--- DateTime: 2021/12/1 5:35 下午
---
--local Hall = class("Hall")
--
--function Hall:ctor()
--    printInfo("Hall ctor")
--end
--
--function Hall.test(number)
--    printInfo("Hall test",number)
--end

Hall = {};
local this = Hall;

function Hall.Awake(gameObject)
    print("Hall Awake ")
    local skipButton = GameObject.Find("SkipButton").gameObject;
    local luaBehaviour = gameObject:GetComponent('LuaBehaviour');
    luaBehaviour:AddClick(skipButton,this.clickEvent)
end

function Hall.Start()
    print("Hall Start ")
end

function Hall.clickEvent()
    printInfo("lua clickEvent")
    SceneManager.LoadScene("SplashScene")
end

